### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by linonetwo** [33357/smartcontract-apps#16]
你好，像 https://github.com/33357/smartcontract-apps/blob/main/GunPool/index.md 如果用 readme。md 作为文件名，在github页面上会直接展示出来，可以试试，效果更好。

加油！

**Comment by 33357** [comment]
已经有readme文件的啊

lin onetwo ***@***.***> 于2022年2月21日周一 00:15写道：

**Comment by linonetwo** [comment]
是建议把 [https://github.com/33357/smartcontract-apps/blob/main/GunPool/index.md](https://github.com/33357/smartcontract-apps/blob/main/GunPool/index.md) 改成用 readme。md 作为文件名，效果会更好

**Comment by linonetwo** [comment]
可以试试看

**Comment by 33357** [comment]
更新了 https://github.com/33357/smartcontract-apps/pull/17

**Comment by linonetwo** [comment]
很棒，加油
