### ISSUE TITLE
UniswapV2Router02中的  function _addLiquidity

### ISSUE THREAD

**Issue by chesterttt** [33357/smartcontract-apps#23]
// reserveA*reserveB/amountADesired，算出实际要添加的 tokenB 数amountBOptimal
        uint amountBOptimal = UniswapV2Library.quote(amountADesired, reserveA, reserveB);

你好，此处应该是这样吧？//amountADesired*reserveB/reserveA

**Comment by 33357** [comment]
是滴，写错了

**Comment by 33357** [comment]
https://github.com/33357/smartcontract-apps/commit/b023e33bc342324ab78d53560c965d9f99a1a9fd

**Comment by 33357** [comment]
修复了
