### ISSUE TITLE
问题讨论

### ISSUE THREAD

**Issue by r4ym0n** [33357/smartcontract-apps#28]
> 在README.md文件中，说 multi_claim合约实现了高效撸（一次交易claim多次）没有EOA机制的合约 对此我没有能够完全理解，特别是做地址预测的目的和 selfdestruct 的使用，希望有知道的大佬们告诉一下，好填完这个坑。

因为这个是使用 合约来模拟用户操作，所以会被撸。 一般会加入EOA检测来排除合约
```
assembly { size := extcodesize(addr) }
```
合约地址预测，为了拿到 new claimer 的地址，用来在调用时候过require 避免白撸。

**Comment by 33357** [comment]
没理解，合约地址预测如何能避免白撸呢
