### ISSUE TITLE
https://33357.github.io/uniswap-v2 无法添加流动性，后续也无法Swap

### ISSUE THREAD

**Issue by studyzy** [33357/smartcontract-apps#41]
我尝试增加了2个ERC20到Uniswap中，添加也成功了
<img width="376" alt="image" src="https://user-images.githubusercontent.com/1635408/222692615-f8c8f71d-2307-494c-b0a1-889dfcc9c0c5.png">
https://goerli.etherscan.io/tx/0xe84019ef81a5daba112ec80858114357b7cc7a12d42f2f6ac8196482be99d5d2
似乎调用的函数不对。最终界面上也没有显示任何交易对：
<img width="439" alt="image" src="https://user-images.githubusercontent.com/1635408/222693057-76f2d8c5-fe3d-4af9-96c4-c6683f61c477.png">

**Comment by 33357** [comment]
修改hash了吗
